blank_issues_enabled: false
contact_links:
  - name: Juan Camilo QHz
    url: https://juancamiloqhz.com/
    about: |
      Please only file issues here that you believe represent actual bugs or feature requests for the AI Workshop.
